#!/bin/bash
# Scan Nextcloud massif, toujours via verrou global. Usage: nas-nc-scan [chemin occ, défaut --all]
ARGS=${1:+--path=$1}; exec /usr/local/sbin/nas-heavy nc-scan docker exec -u www-data nextcloud-app-1 nice -n19 php -d memory_limit=1G occ files:scan ${ARGS:---all}
